version: 2

sources:
- name: staging
  database: atomic-voice-338721
  schema: trips_data_all

  tables:
  - name: green_tripdata
- name: staging_yellow
  database: atomic-voice-338721
  schema: nytaxi

  tables:
  - name: yellow_tripdata
